version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - pet-adoption-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    environment:
      - MONGO_URI
      - DATABASE_NAME
    networks:
      - pet-adoption-network

networks:
  pet-adoption-network:
    driver: bridge
